apiVersion: mariak8g.mariadb.org/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-sample
spec:
  # Add required fields:
  dataStoragePath: "/tmp/datadir"
  database: "testDB-operator"
  password: "my_cool_secret"
  rootpwd: "my-secret-pw"
  username: "example-user"

  # Optional fields
  replicas: 2
  imageVersion: "10.6"
  image: "quay.io/mariadb-foundation/mariadb-devel:10.5"
  
