apiVersion: mariak8g.mariadb.org/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-sample
spec:
  # Add required fields:
  dataStoragePath: "/tmp/datadir"
  database: "testDB-operator"
  image: "docker-image"
  password: "test!123"
  rootpwd: "root!123"
  username: "anel"
  
